dist: precise
language: python
python:
  - "3.5"
  - "3.6"
  - "nightly"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python3-apt
install:
  - "pip3 install -r requirements.txt"
script: pytest
