sudo: required 
language: python
services:
  - docker
install:
  - docker pull ubuntu:16.04
script:
  - pwd
  - ls -al
  - docker run -v $(pwd):/edi-debuild ubuntu:16.04 bash -c "cd /edi-debuild/ && cat do_release"
